travis:
  secure:
    BINSTAR_TOKEN: UTzadGsl+9JRPtIISH3JEEd2cOeLaMI+A9Ync485GYZRn7H8bD77SYoUhhbxlEsCuTrgotcmHi8EX/7vQDstl7o5hsj8XM6DO4Mew9RVzWxCONVAA7HqkthLgUojTsR4+GDOlX0PtlNL0lKZQ8q4VRXbKWkvIIkbVMV428N4MTNjtrH+5Axm6PP9jpA6eqikqOEuhdQDgTdMx/hWn3kySRrovp+2aZEH2k4LPozpumwR2Mdhyf+xHuuL5TYaShEUue6QmXS0wYwz0PoMqu+GDWbHqeHG3z/nNYKY5y3Qk1mEEVzIDHNtLZDQnFnhAHJkM+1xnuvGbzKCos1AjOIgI/pyWrtk3wboEkudbc6T1UZDcHc7Xoortx4R2us/0xolIMAiG6YbS9LwKwiZ5G09ivnw0DkUi5dkjv0t2HVxGfRydy3dr22NdPqa9fsy523N2Ih9j/um2khbnzMzfTXz1VixW2ip2FXnfkhS71D6jWya3xRHNsqm0Tzx8jWcdqitU0n9VMuu8hWvNw2FbZEDACZxEHsMH3qpmDSaQTO3Ll+Z2eE6mD7gm5n2yPasdPvIQNECgjWNcHo8LkD65OSJqzUhp7C6A26rGCy+vPpR1LjVG5ODgxmyuHhvyZN6+aQrDqyTRTlHVz5XGPlpbaKVUVozFb+oUmutshDZrnOqXdk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
