travis:
  secure:
    BINSTAR_TOKEN: pRmkvOnX6EhioTgPRfOaIJ9OR7m0I0ptGwo+bhnjkMUiDi/gcARePCJTl5bHoDnWZfeF/HrAGFkTncvs1SZCqgIdvHsv9K5+558A+YeRcyFJrpsGwb1Qu855bmPe17PCXGdibnkqSXt4CXBW2DBLpA1L626H2m/ozHknds8KseU9B1GRJHTHQqZSOsKAApOLWKPDBl5nymvmD4TsHRZyENwsES+Duddz7G8zURTOaOhtqnX9A0tNOp0VXlrcONyisAqwjppY7g+51U0fiwhhOj9I9pxOirnzgk8qHw2iSDwp2aJ6cei7e9BdDLaW8TcdvZstzRRVFtQakb028wBIsW23BYdiUgRmhRdgofDeVUk4GrFJp2IDxbskl1lm8bYBbf7ZTVDUMZcELz0b+ktFWx0EMG2uKS3trRFbWLFyeMg+cAc9ml+W2JgVb8nJ6ozVklfsbMUO5A8Vxrf6G0uYCk9FZURv4FGqqzDpyH9E3z8JGJEWMVrTCoFKSrIfcijTxq7SVAuGMATmnxwAROhuM+FvjSujiwlZVw6RwjZlYxc6pMTraQYicO9Qqr+TFF9jtEa8IEz8S2jvSMyI5LPohSxVcI1vRksogUxaTlTlf7G9Ovy18ilPVeTb3Ydw98+bFQT1b6JJ1XlxBSyI9V1B0wXuJ3pifTjZsnjKHSUjEjk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
